CoreBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            column: username
        email:
            type: string
            length: 255
            column: email
        password:
            type: string
            length: 255
            column: password
        isActive:
            type: boolean
            column: isActive
    lifecycleCallbacks: {  }
