CoreBundle\Entity\User:
    type: entity
    table: users
    id:
        Id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            column: Name
        Email:
            type: string
            length: 255
            column: Email
        Password:
            type: string
            length: 255
            column: Password
        Status:
            type: boolean
            column: Status
    lifecycleCallbacks: {  }
