user_get_list:
    path:     /api/users
    defaults: { _controller: ApiBundle:Users:getList }
    methods: [GET]

trl:
    path:      /trl
    # uses a special syntax to point to the controller - see note below
    defaults:  { _controller: ApiBundle:Users:Test }
