<?php

namespace CoreBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DBContext // \Doctrine\ORM\EntityRepository
{
    private $_ctx;

    function __construct($entityManager)
    {
        $this->_ctx = $entityManager;
    }

    public function SaveChanges()
    {
        $this->_ctx->persist();
        $this->_ctx->flush();
    }
}

?>